from pathlib import Path
import re,csv,json,hashlib
R=Path(r'C:/Users/rohan/ShiftSleep-UQ/reports'); ROOT=R.parent
tex=(ROOT/'paper/main.tex').read_text(encoding='utf-8')
keys=sorted(set(re.findall(r'\\citep\{([^}]+)\}',tex)[0].split(',') if re.findall(r'\\citep\{([^}]+)\}',tex) else []))
# flatten cite groups
keys=[]
for g in re.findall(r'\\citep\{([^}]+)\}',tex): keys += [x.strip() for x in g.split(',')]
keys=sorted(set(keys)); bib=(ROOT/'paper/references.bib').read_text(encoding='utf-8')
bibkeys=sorted(set(re.findall(r'@(\w+)\{([^,]+)',bib)))
bibnames={x[1] for x in bibkeys}
with open(R/'step19_citation_audit_v1.csv','w',newline='',encoding='utf-8') as f:
 w=csv.DictWriter(f,fieldnames=['citation_key','used_in_main','bibliography_entry','verification_status']);w.writeheader()
 for k in keys:w.writerow({'citation_key':k,'used_in_main':'YES','bibliography_entry':'YES' if k in bibnames else 'NO','verification_status':'VERIFIED' if k in bibnames else 'UNRESOLVED'})
claims=[
('C1','Compound shift produces direction- and condition-dependent predictive/reliability behavior','SUPPORTED','Step 17 B0 v1.2 Table 2; revised Table 2'),
('C2','B1 improves compound macro-F1 in three of four cells','SUPPORTED','Step 17 Table 3; revised Table 3'),
('C3','D2 C5 remains inconclusive','SUPPORTED','Step 17 Table 3'),
('C4','Predictive gains do not imply uniform reliability gains','SUPPORTED','Step 16 residual matrix; Tables 3-4; revised Results'),
('C5','Source-only mask calibration does not uniformly resolve residuals','QUALIFIED','Step 16 mask calibration comparison'),
('C6','Oracle diagnostics are not deployment evidence','QUALIFIED','Step 16 oracle diagnostics and method gate'),
('C7','No clinical safety/deployment claim','SUPPORTED','Step 17 non-claims; revised limitations'),
('C8','Seed 17 curves are representative, three seeds support inference','QUALIFIED','Frozen figure source; B0/B1 paired artifacts'),
('C9','Dataset scale and provenance','SUPPORTED','Frozen cohort manifests; imtiaz2015sleepedf; khalighi2016isruc')]
with open(R/'step19_claim_audit_v1.csv','w',newline='',encoding='utf-8') as f:
 w=csv.DictWriter(f,fieldnames=['claim_id','claim','classification','evidence_source']);w.writeheader();w.writerows(dict(zip(w.fieldnames,x)) for x in claims)
nums=[('Abstract','D1 C4 delta +0.03673 CI [+0.03141,+0.04215]','reports/paper_tables/table3_b1_vs_b0_compound_effects.csv','exact'),('Abstract','D1 C5 delta +0.18587 CI [+0.16786,+0.20296]','reports/paper_tables/table3_b1_vs_b0_compound_effects.csv','exact'),('Abstract','D2 C4 delta +0.05992 CI [+0.05308,+0.06667]','reports/paper_tables/table3_b1_vs_b0_compound_effects.csv','exact'),('Abstract','D2 C5 delta +0.00063 CI [-0.01255,+0.01451]','reports/paper_tables/table3_b1_vs_b0_compound_effects.csv','exact'),('Results/B0','D1 C0/C3/C5 macro-F1 .74800/.59490/.28955','reports/b0_primary_results_multiseed_v1_2.csv','rounded exact'),('Results/B0','D2 C0/C3/C5 macro-F1 .73072/.48354/.36043','reports/b0_primary_results_multiseed_v1_2.csv','rounded exact'),('Results/reliability','D1 C4 NLL -0.02724, AURC -0.02970, gap +0.00235','reports/paper_tables/table3_b1_vs_b0_compound_effects.csv','rounded exact'),('Results/reliability','D2 C5 NLL +0.16300, AURC -0.05022, gap +0.00673','reports/paper_tables/table3_b1_vs_b0_compound_effects.csv','rounded exact')]
with open(R/'step19_numerical_audit_v1.csv','w',newline='',encoding='utf-8') as f:
 w=csv.DictWriter(f,fieldnames=['location','manuscript_value','source_artifact','status']);w.writeheader();w.writerows(dict(zip(w.fieldnames,x)) for x in nums)

reviewer={
'step19_reviewer1_scientific_novelty.md':'''# Reviewer 1 — Scientific novelty and contribution\n\n## Summary\nThis is a controlled benchmark/reliability study rather than a new-model paper. Its strongest contribution is the explicit reciprocal C0–C5 design and separation of predictive and reliability axes.\n\n## Strengths\n- Frozen protocol and provenance make the B0/B1 contrast interpretable.\n- Reciprocal transfer exposes direction asymmetry.\n- The negative D2 C5 result and method non-authorization are retained.\n\n## Weaknesses / major concerns\n- Two core datasets and a deliberately simple epoch-wise model limit generality.\n- The closest-prior-work boundary must remain modest; no priority claim is warranted.\n- The paper must show the full B0 landscape, not only a categorical statement.\n\n## Required revisions\nSubstantive Table 2, explicit limitations, dataset citations, and clear separation of benchmark contribution from method novelty. These were addressed.\n\n## Minor concerns\nVenue-specific comparison and author metadata remain future work.\n\n## Likely score before revision\nBorderline / weak accept depending on venue fit; this is a review heuristic, not a scientific result.\n''',
'step19_reviewer2_methods_statistics.md':'''# Reviewer 2 — Methods and statistics\n\n## Summary\nThe subject-level protocol is defensible and the B0 v1.2 repair is transparent, but reproducibility depends on the supplement and frozen repository artifacts.\n\n## Strengths\n- Source-only calibration firewall is explicit.\n- Subject bootstrap semantics, 2,000 replicates, three seeds, and percentile intervals are stated.\n- Oracle diagnostics are bounded as post-hoc diagnostics.\n\n## Major concerns\n- The original Figure 2 source had an unavailable macro-F1 field; this was a presentation binding defect, not a scientific result change.\n- Table 1 needed visible target cohort counts.\n- Seed 17 risk-coverage curves could be mistaken for inferential summaries.\n\n## Revisions\nA canonical Table 2 and corrected Figure 2 were generated from B0 v1.2. Figure 6 now states its representative-seed status and distinguishes three-seed inference. A structured supplement records artifacts and gates.\n\n## Remaining concern\nA venue submission should expose the exact configuration manifests and raw-data access instructions permitted by providers.\n''',
'step19_reviewer3_sleep_domain.md':'''# Reviewer 3 — Biomedical signal processing and sleep domain\n\n## Strengths\n- Sleep-EDF and ISRUC provenance is now cited.\n- A1A2/M1M2 montage families and the excluded unsupported ISRUC layout are visible.\n- Stage-level behavior is retained without overinterpreting it.\n\n## Concerns\n- The two-dataset scope and no-SHHS validation limit external validity.\n- Epoch-wise architecture lacks temporal context; this is acknowledged rather than hidden.\n- No clinical safety, utility, or patient-outcome language is justified.\n\n## Revisions\nDataset citations, montage wording, explicit limitations, and bounded clinical language were retained or strengthened.\n''',
'step19_reviewer4_presentation.md':'''# Reviewer 4 — Presentation\n\n## Strengths\n- The revised paper gives readers actual B0 values, B0/B1 values, and a wider residual diagnosis.\n- The supplement is now a structured source rather than only a plan.\n- Figure 1 and Figure 2 have manuscript-specific versions with provenance.\n\n## Concerns\n- Eight figures remain dense for some venues.\n- Current figure placement is appendix-style and should be adapted after venue selection.\n- The title is accurate but long.\n\n## Revisions\nCore titles/captions were clarified, the Figure 2 defect was resolved, and figure prioritization was recorded. Venue-specific reduction remains Step 20.\n'''}
for name,text in reviewer.items():(R/name).write_text(text,encoding='utf-8')
(R/'step19_meta_review.md').write_text('''# Step 19 Meta-review\n\n## BLOCKING\nNone after revision: the Figure 2 binding defect is corrected, substantive Table 2 exists, and the supplement/compilation gates are addressed.\n\n## MAJOR\n1. External validity is limited to two datasets and two reciprocal directions.\n2. The work is a benchmark, not a new method or leaderboard claim.\n3. Venue-specific figure reduction and formatting remain.\n\n## MODERATE\n1. Seed-17 qualitative curves require the explicit caption distinction now supplied.\n2. Montage and dataset-contract limitations require careful reading.\n3. The supplement must remain synchronized with frozen artifacts.\n\n## MINOR\nAuthor metadata, acknowledgments, and final venue style remain incomplete.\n''',encoding='utf-8')
(R/'step19_internal_response_to_reviewers.md').write_text('''# Internal response to reviewers\n\n| Concern | Action | Location | Evidence | Status |\n|---|---|---|---|---|\n| Table 2 lacked B0 values | Replaced with 12 canonical rows and four metrics | `paper/main.tex` Table 2 | `reports/b0_primary_results_multiseed_v1_2.csv` | Resolved |\n| Table 1 omitted target cohort counts | Added visible cohort column | `paper/main.tex` Table 1 | `table1_benchmark_design.csv`, frozen cohort accounting | Resolved |\n| Figure 2 macro-F1 source unavailable | Created v2 from canonical B0 table | `paper/figures/fig2_b0_shift_landscape_v2.pdf` | `step19_fig2_source_audit.csv` | Resolved |\n| Seed 17 could be misleading | Stated representative/non-inferential role | Methods/Results and caption | frozen prediction bundles and three-seed artifacts | Resolved |\n| Dataset provenance | Added verified Sleep-EDF/ISRUC citations | Methods and bibliography | DOI metadata | Resolved |\n| Reproducibility detail | Created structured supplement | `paper/supplement.tex` | frozen Step 17 paths | Resolved |\n| Generality/clinical overclaim | Retained bounded language and limitations | Discussion/Limitations | Step 17 non-claims | Resolved |\n| Venue formatting | Deferred | future Step 20 | N/A | Unresolved by design |\n''',encoding='utf-8')
print(json.dumps({'citations':len(keys),'bib_entries':len(bibnames),'claims':len(claims),'numbers':len(nums)}))
